### ISSUE TITLE
Renaming a todo task is being resemblance to other tasks 

### ISSUE THREAD

**Issue by Karthikeya-kumar** [ryojp/todo#15] opened 2022-10-03 08:24 UTC
#15
While Renaming an already existing task is resulting in name changing to all other tasks in the list. @keikekke

**Comment by ryojp** [comment] 2022-10-03 12:59
Hello, and thank you very much for filing an issue!  
Could you give me little more details on how to reproduce this issue?  @Karthikeya-kumar 

In my understanding, your situation is
- Create three different tasks, for example
- Rename the second one with the same name as the first one
- This results in the other two tasks having the same name as what the selected task should be renamed to, leaving the selected task unchanged

However, when I just tested this on the demo page, I could successfully rename only the selected one. There is no validation to confirm uniqueness right now, though.

**Comment by ryojp** [comment] 2022-10-12 10:07
Since it's been more than a week and this issue cannot be reproduced, I'll close this. Reopen it if necessary.

**Closed as not planned by ryojp** 2022-10-12 10:07 UTC
